CREATE TABLE Categories (
    Id BIGINT NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(500) NULL,
    IsActive TINYINT(1) NOT NULL DEFAULT 1,
    CreatedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
    UpdatedAt DATETIME NULL,

    CONSTRAINT PK_Categories PRIMARY KEY (Id),
    CONSTRAINT UQ_Categories_Name UNIQUE (Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;